stages:
  - build
  - deploy

variables:
  DEPLOY_DIR: "/opt/tms-admin-be"

# Cấu hình Build
build:
  stage: build
  tags:
    - runner-vpd-que
  script:
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm install --frozen-lockfile
    - pnpm run build
  artifacts:
    paths:
      - .next/
      - public/
      - node_modules/
      - package.json
      - pnpm-lock.yaml
      - ecosystem.config.js
    expire_in: 1 hour
  only:
    - release/staging

# Cấu hình Deploy
deploy:
  stage: deploy
  tags:
    - runner-vpd-que
  script:
    # Xóa tiến trình cũ
    - pm2 delete tms-admin-be || true
    # Đồng bộ file
    - mkdir -p $DEPLOY_DIR
    - cp -r ./.next $DEPLOY_DIR/
    - cp -r ./public $DEPLOY_DIR/
    - cp -r ./node_modules $DEPLOY_DIR/
    - cp package.json $DEPLOY_DIR/
    - cp pnpm-lock.yaml $DEPLOY_DIR/
    - cp ecosystem.config.js $DEPLOY_DIR/
    # Khởi động app
    - cd $DEPLOY_DIR
    - pm2 start ecosystem.config.js --env production
  only:
    - release/staging