import type {
  CeoOverview,
  EmployeePerformance,
  CeoAlert,
  AiExtractionSummary,
  DepartmentSummary,
  ReportRow,
} from "./types"

export const ceoOverviewMock: CeoOverview = {
  totalEmails: 238,
  totalAttachments: 412,
  totalTasks: 186,
  completedTasks: 142,
  processingTasks: 31,
  pendingTasks: 13,
  overdueTasks: 8,
  aiSuccessRate: 82,
  completionRate: 76,
  reportRows: 150,
  missingDataRows: 12,
}

export const ceoEmployeesMock: EmployeePerformance[] = [
  {
    id: "emp-001",
    name: "Nguyễn Văn A",
    department: "Chứng từ",
    role: "Nhân viên chứng từ",
    email: "nguyenvana@thongquan.com.vn",
    totalEmails: 156,
    totalTasks: 120,
    completedTasks: 95,
    processingTasks: 18,
    pendingTasks: 2,
    overdueTasks: 5,
    completionRate: 79,
    averageProcessingTime: "18 phút",
    aiExtractedFiles: 86,
    aiNeedReviewFiles: 14,
    customers: [
      {
        customerName: "Công ty A",
        totalEmails: 35,
        totalTasks: 28,
        processingTasks: 5,
        overdueTasks: 1,
      },
      {
        customerName: "Công ty B",
        totalEmails: 22,
        totalTasks: 18,
        processingTasks: 3,
        overdueTasks: 0,
      },
    ],
    currentTasks: [
      {
        id: "TK-001",
        customerName: "Công ty A",
        emailSubject: "INV Công ty A - Bill 123",
        documentType: "Invoice",
        status: "processing",
        receivedAt: "2026-05-29 08:30",
        dueAt: "2026-05-29 10:30",
        warning: "Bình thường",
      },
      {
        id: "TK-003",
        customerName: "Công ty C",
        emailSubject: "Tờ khai nhập khẩu - Booking 456",
        documentType: "Tờ khai",
        status: "overdue",
        receivedAt: "2026-05-29 07:20",
        dueAt: "2026-05-29 09:20",
        warning: "Quá hạn 45 phút",
      },
    ],
    emails: [
      { receivedAt: "08:15", subject: "INV Công ty A - Bill 123", customerName: "Công ty A", attachments: 3, aiStatus: "Thành công", status: "Đã tạo task" },
      { receivedAt: "09:00", subject: "Booking Công ty B", customerName: "Công ty B", attachments: 2, aiStatus: "Thiếu dữ liệu", status: "Cần kiểm tra" },
    ],
    activityLogs: [
      { time: "08:30", action: "Nhận task", content: "Nhận xử lý email INV Công ty A" },
      { time: "08:35", action: "AI bóc tách", content: "Bóc tách thành công invoice" },
      { time: "08:45", action: "Cập nhật trạng thái", content: "Chuyển sang đang xử lý" },
      { time: "09:20", action: "Ghi chú", content: "Thiếu thông tin booking, chờ khách bổ sung" },
    ],
  },
  {
    id: "emp-002",
    name: "Trần Thị B",
    department: "Khai báo",
    role: "Nhân viên khai báo",
    email: "tranthib@thongquan.com.vn",
    totalEmails: 120,
    totalTasks: 98,
    completedTasks: 88,
    processingTasks: 6,
    pendingTasks: 1,
    overdueTasks: 3,
    completionRate: 89,
    averageProcessingTime: "14 phút",
    aiExtractedFiles: 72,
    aiNeedReviewFiles: 8,
    customers: [
      {
        customerName: "Công ty C",
        totalEmails: 28,
        totalTasks: 24,
        processingTasks: 4,
        overdueTasks: 1,
      },
    ],
    currentTasks: [
      {
        id: "TK-005",
        customerName: "Công ty C",
        emailSubject: "Booking xuất khẩu Công ty C",
        documentType: "Booking",
        status: "processing",
        receivedAt: "2026-05-29 09:00",
        dueAt: "2026-05-29 11:00",
        warning: "Bình thường",
      },
    ],
    emails: [
      { receivedAt: "09:30", subject: "Tờ khai xuất khẩu Công ty C", customerName: "Công ty C", attachments: 4, aiStatus: "Thành công", status: "Đang xử lý" },
    ],
    activityLogs: [
      { time: "09:00", action: "Nhận task", content: "Nhận booking xuất khẩu Công ty C" },
      { time: "09:10", action: "AI bóc tách", content: "Bóc tách thành công" },
    ],
  },
  {
    id: "emp-003",
    name: "Lê Văn C",
    department: "Nghiệp vụ",
    role: "Nhân viên nghiệp vụ",
    email: "levanc@thongquan.com.vn",
    totalEmails: 90,
    totalTasks: 75,
    completedTasks: 40,
    processingTasks: 25,
    pendingTasks: 4,
    overdueTasks: 6,
    completionRate: 53,
    averageProcessingTime: "35 phút",
    aiExtractedFiles: 45,
    aiNeedReviewFiles: 22,
    customers: [
      {
        customerName: "Công ty D",
        totalEmails: 30,
        totalTasks: 25,
        processingTasks: 8,
        overdueTasks: 3,
      },
    ],
    currentTasks: [
      {
        id: "TK-008",
        customerName: "Công ty D",
        emailSubject: "Bill lading Công ty D",
        documentType: "Bill",
        status: "overdue",
        receivedAt: "2026-05-29 06:00",
        dueAt: "2026-05-29 08:00",
        warning: "Quá hạn 2 giờ",
      },
    ],
    emails: [
      { receivedAt: "06:30", subject: "Bill lading Công ty D", customerName: "Công ty D", attachments: 2, aiStatus: "Cần review", status: "Quá hạn" },
    ],
    activityLogs: [
      { time: "06:00", action: "Nhận task", content: "Nhận bill lading Công ty D" },
      { time: "07:00", action: "Cảnh báo quá hạn", content: "Task quá hạn 1 giờ" },
    ],
  },
  {
    id: "emp-004",
    name: "Phạm Thị D",
    department: "Kế toán",
    role: "Nhân viên kế toán",
    email: "phamthid@thongquan.com.vn",
    totalEmails: 70,
    totalTasks: 60,
    completedTasks: 52,
    processingTasks: 5,
    pendingTasks: 1,
    overdueTasks: 2,
    completionRate: 86,
    averageProcessingTime: "20 phút",
    aiExtractedFiles: 48,
    aiNeedReviewFiles: 6,
    customers: [
      {
        customerName: "Công ty E",
        totalEmails: 20,
        totalTasks: 18,
        processingTasks: 2,
        overdueTasks: 0,
      },
    ],
    currentTasks: [],
    emails: [
      { receivedAt: "10:00", subject: "Invoice Công ty E", customerName: "Công ty E", attachments: 1, aiStatus: "Thành công", status: "Hoàn tất" },
    ],
    activityLogs: [
      { time: "10:00", action: "Hoàn tất", content: "Xử lý xong invoice Công ty E" },
    ],
  },
]

export const ceoAlertsMock: CeoAlert[] = [
  {
    id: "alert-001",
    type: "overdue_task",
    level: "high",
    title: "Nguyễn Văn A có 5 task quá hạn",
    description: "Cần kiểm tra các task đang pending quá SLA.",
    relatedEmployeeId: "emp-001",
    relatedTaskIds: ["TK-003", "TK-010"],
    createdAt: "2026-05-29 10:30",
  },
  {
    id: "alert-002",
    type: "unprocessed_email",
    level: "medium",
    title: "Có 12 email chưa được xử lý",
    description: "Các email này chưa được tạo task hoặc chưa có người phụ trách.",
    createdAt: "2026-05-29 11:00",
  },
  {
    id: "alert-003",
    type: "employee_overload",
    level: "medium",
    title: "Lê Văn C đang xử lý 25 task",
    description: "Nhân viên này có workload cao hơn bình thường, cần theo dõi.",
    relatedEmployeeId: "emp-003",
    createdAt: "2026-05-29 09:45",
  },
  {
    id: "alert-004",
    type: "missing_data",
    level: "high",
    title: "Công ty ABC có 3 hồ sơ thiếu dữ liệu báo cáo",
    description: "Dữ liệu thiếu có thể ảnh hưởng đến kế toán/công nợ.",
    createdAt: "2026-05-29 08:20",
  },
]

export const aiExtractionSummaryMock: AiExtractionSummary = {
  totalFiles: 1240,
  success: 980,
  needReview: 210,
  failed: 50,
  successRate: 79,
  byDocumentType: [
    {
      documentType: "Invoice",
      total: 520,
      success: 450,
      needReview: 55,
      failed: 15,
      successRate: 86.5,
    },
    {
      documentType: "Bill",
      total: 310,
      success: 250,
      needReview: 45,
      failed: 15,
      successRate: 80.6,
    },
    {
      documentType: "Booking",
      total: 220,
      success: 170,
      needReview: 38,
      failed: 12,
      successRate: 77.2,
    },
    {
      documentType: "Tờ khai",
      total: 190,
      success: 110,
      needReview: 72,
      failed: 8,
      successRate: 57.9,
    },
  ],
}

export const departmentSummaryMock: DepartmentSummary[] = [
  {
    name: "Chứng từ",
    totalTasks: 520,
    completedTasks: 410,
    processingTasks: 80,
    overdueTasks: 30,
    completionRate: 78.8,
    alert: "Cần theo dõi",
  },
  {
    name: "Khai báo",
    totalTasks: 380,
    completedTasks: 320,
    processingTasks: 45,
    overdueTasks: 15,
    completionRate: 84.2,
    alert: "Ổn định",
  },
  {
    name: "Kế toán",
    totalTasks: 160,
    completedTasks: 130,
    processingTasks: 20,
    overdueTasks: 10,
    completionRate: 81.2,
    alert: "Cần kiểm tra",
  },
  {
    name: "Nghiệp vụ",
    totalTasks: 240,
    completedTasks: 190,
    processingTasks: 35,
    overdueTasks: 15,
    completionRate: 79.1,
    alert: "Cần theo dõi",
  },
]

export const reportSummaryMock: ReportRow[] = [
  {
    stt: 1,
    customerName: "Công ty A",
    invoice: "INV001",
    bill: "BILL001",
    booking: "BK001",
    type: "Nhập",
    employee: "Nguyễn Văn A",
    status: "Hoàn tất",
    receivedDate: "29/05/2026",
    completedDate: "29/05/2026",
    notes: "Đủ dữ liệu",
  },
  {
    stt: 2,
    customerName: "Công ty B",
    invoice: "INV002",
    bill: "BILL002",
    booking: "BK002",
    type: "Xuất",
    employee: "Trần Thị B",
    status: "Đang xử lý",
    receivedDate: "29/05/2026",
    completedDate: "-",
    notes: "Chờ khách",
  },
  {
    stt: 3,
    customerName: "Công ty C",
    invoice: "INV003",
    bill: "BILL003",
    booking: "BK003",
    type: "Nhập",
    employee: "Lê Văn C",
    status: "Quá hạn",
    receivedDate: "29/05/2026",
    completedDate: "-",
    notes: "Thiếu booking",
  },
]
